# Generated by Django 4.2.3 on 2023-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_company_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partner',
            field=models.CharField(default='SLAS', max_length=100),
        ),
    ]
