# Generated by Django 4.2.3 on 2023-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_company_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Folha de Pagamento'), ('Vacations', 'Férias'), ('Termination', 'Rescisão'), ('Requests', 'Solicitações'), ('Changes', 'Alterações'), ('News', 'Novidades'), ('Charges', 'Encargos'), ('WorkOrder', 'WorkOrder'), ('Requests', 'Duvidas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, choices=[('operation', 'Operação'), ('developer', 'Desenvolvimento'), ('administration', 'Administration')], default='operation', max_length=100, null=True),
        ),
    ]
