# Generated by Django 4.2.3 on 2023-07-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_by',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_close', to=settings.AUTH_USER_MODEL),
        ),
    ]
