# Generated by Django 4.2.3 on 2023-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, choices=[('operation', 'Operation'), ('developer', 'Developer'), ('administration', 'Administration')], default='operation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('scheduled', 'Scheduled')], default='medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Vacations', 'Vacations'), ('Termination', 'Rescisão'), ('Requests', 'Termination'), ('Changes', 'Changes'), ('News', 'News'), ('Charges', 'Charges'), ('WorkOrder', 'WorkOrder'), ('Requests', 'Requests')], max_length=100, null=True),
        ),
    ]
