# Generated by Django 4.2.3 on 2023-07-30 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_attachment_alter_ticket_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField()),
                ('changes', models.DateField(blank=True, null=True)),
                ('payroll_preview', models.DateField(blank=True, null=True)),
                ('approval', models.DateField(blank=True, null=True)),
                ('net_salaries', models.DateField(blank=True, null=True)),
                ('taxes', models.DateField(blank=True, null=True)),
                ('accounting', models.DateField(blank=True, null=True)),
                ('next_month_vacations', models.DateField(blank=True, null=True)),
                ('esocial_delivery', models.DateField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_deliveries', to=settings.AUTH_USER_MODEL)),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_deliveries', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.company')),
            ],
        ),
    ]
