# Generated by Django 4.2.3 on 2023-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_rename_accounting_deliverycalendar_accounting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycalendar',
            name='pay_period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Advance', 'Advance')], default='monthly', max_length=15),
        ),
    ]
