# Generated by Django 4.2.3 on 2023-07-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_deliverycalendar_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='analyst',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_analysts', to='tickets.CustomUser', default='10', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='analyst_backup',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_analysts_backup', to='tickets.CustomUser', default='10', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cams', to='tickets.CustomUser', default='10', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cam_backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cams_backup', to='tickets.CustomUser', default='10', null=True),
        ),
        migrations.AlterField(
            model_name='deliverycalendar',
            name='pay_period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Advance', 'Advance')], default='Monthly', max_length=15),
        ),
    ]
