# Generated by Django 4.2.3 on 2023-07-30 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_company_analyst_company_analyst_backup_company_cam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='analyst',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='company_analysts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='analyst_backup',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='company_analysts_backup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='cam',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='company_cams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='cam_backup',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='company_cams_backup', to=settings.AUTH_USER_MODEL),
        ),
    ]
