# Generated by Django 4.2.3 on 2023-07-30 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_company_analyst_alter_company_analyst_backup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_analysts', to=settings.AUTH_USER_MODEL),
        ),
    ]
