# Generated by Django 4.2.3 on 2023-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_company_analyst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Waiting on contact', 'Waiting on contact'), ('Waiting on us', 'Waiting on us'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Vacations', 'Vacations'), ('Termination', 'Termination'), ('Requests', 'Requests'), ('Changes', 'Changes'), ('Taxes', 'Taxes'), ('WorkOrder', 'Work Order'), ('Accounting', 'Accounting'), ('esocial', 'eSocial')], max_length=100, null=True),
        ),
    ]
