# Generated by Django 4.2.3 on 2023-08-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_change_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, choices=[('Operation', 'Operation'), ('Tecnology', 'Tecnology'), ('Administration', 'Administration'), ('Services', 'Services'), ('Accounting', 'Accounting')], default='Operation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent'), ('Scheduled', 'Scheduled')], default='Medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Vacations', 'Vacations'), ('Termination', 'Termination'), ('Requests', 'Requests'), ('Changes', 'Changes'), ('Taxes', 'Taxes'), ('esocial', 'eSocial'), ('Payroll Requests', 'Payroll Requests'), ('Sick Leave', 'Sick Leave'), ('Paylips Dashboard', 'Paylips Dashboard'), ('Payroll Requests', 'Payroll Requests'), ('Payroll Support', 'Payroll Support'), ('Payrrol Accounting', 'Payroll Accounting'), ('Work Order', 'Work Order'), ('Customization (IT)', 'Customization(IT)'), ('Functionality correction(IT)', 'Functionality correction(IT)'), ('Rule Replication(IT)', 'Rule Replication(IT)'), ('User support (IT)', 'User support (IT)'), ('Provisions', 'Provisions'), ('Accounting Support', 'Accounting Support')], max_length=100, null=True),
        ),
    ]
