# Generated by Django 4.2.3 on 2023-08-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_deliverycalendar_analyst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycalendar',
            name='cam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
