# Generated by Django 4.2.3 on 2023-08-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_deliverycalendar_cam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_report', models.BooleanField(default=False)),
                ('naming_convention', models.BooleanField(default=False)),
                ('delivery_format', models.BooleanField(default=False)),
                ('delivery_date', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.company')),
            ],
        ),
    ]
