# Generated by Django 4.2.3 on 2023-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_deliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='delivery_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='delivery_format',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='frequency',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='naming_convention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='payroll_report',
            field=models.TextField(),
        ),
    ]
