# Generated by Django 4.2.3 on 2023-08-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_deliverable_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Vacations', 'Vacations'), ('Termination', 'Termination'), ('New Hires', 'New Hires'), ('13th Salary', '13th Salary'), ('Taxes', 'Taxes'), ('Annual Statutary Declarations', 'Annual Statutary Declarations'), ('Accounting', 'Accounting')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, choices=[('Payroll', 'Payroll'), ('Vacations', 'Vacations'), ('Termination', 'Termination'), ('New Hire', 'New Hire'), ('Requests', 'Requests'), ('Changes', 'Changes'), ('Taxes', 'Taxes'), ('esocial', 'eSocial'), ('Payroll Requests', 'Payroll Requests'), ('Sick Leave', 'Sick Leave'), ('Paylips Dashboard', 'Paylips Dashboard'), ('Payroll Requests', 'Payroll Requests'), ('Payroll Support', 'Payroll Support'), ('Payrrol Accounting', 'Payroll Accounting'), ('Work Order', 'Work Order'), ('Customization (IT)', 'Customization(IT)'), ('Functionality correction(IT)', 'Functionality correction(IT)'), ('Rule Replication(IT)', 'Rule Replication(IT)'), ('User support (IT)', 'User support (IT)'), ('Provisions', 'Provisions'), ('Accounting Support', 'Accounting Support')], max_length=100, null=True),
        ),
    ]
