# Generated by Django 4.2.3 on 2023-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_deliverable_type_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='delivery_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='delivery_format',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='naming_convention',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='payroll_report',
            field=models.CharField(max_length=100),
        ),
    ]
