# Generated by Django 4.2.3 on 2023-08-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_alter_deliverable_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='type',
            new_name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='delivery_date',
        ),
    ]
