# Generated by Django 4.2.3 on 2023-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_rename_type_deliverable_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('On Demand', 'On Demand'), ('Annually', 'Annually'), ('New Hires', 'New Hires'), ('13th Salary', '13th Salary'), ('Taxes', 'Taxes'), ('Annual Statutary Declarations', 'Annual Statutary Declarations'), ('Accounting', 'Accounting')], max_length=100, null=True),
        ),
    ]
