# Generated by Django 4.2.3 on 2023-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_deliverable_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='delivery_date',
            field=models.CharField(blank=True, choices=[('Per event', 'Per event'), ('Per payroll run', 'Per payroll run'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('On Demand', 'On Demand'), ('Annually', 'Annually')], max_length=100, null=True),
        ),
    ]
