# Generated by Django 4.2.3 on 2023-08-09 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_deliverable_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Operation', 'Operation'), ('Tecnology', 'Tecnology'), ('Administration', 'Administration'), ('Services', 'Services'), ('Accounting', 'Accounting')], default='Services', max_length=100, null=True)),
                ('hours', models.CharField(max_length=10)),
                ('cam_approval', models.CharField(max_length=50)),
                ('analyst_approval', models.CharField(max_length=50)),
                ('billing', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('Waiting on contact', 'Waiting on contact'), ('Waiting on us', 'Waiting on us'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('sla_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('Work Order', 'Work Order'), ('RSA', 'RSA')], max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workorder', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workorder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
