# Generated by Django 4.2.3 on 2023-08-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
