# Generated by Django 4.2.3 on 2023-08-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_workorder_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
