# Generated by Django 4.2.3 on 2023-08-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_workorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent'), ('Scheduled', 'Scheduled')], default='Medium', max_length=15),
        ),
    ]
