# Generated by Django 4.2.3 on 2023-08-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_workorder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='analyst_approval',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reprove', 'Reprove')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cam_approval',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reprove', 'Reprove')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Waiting on contact', 'Waiting on contact'), ('Waiting on us', 'Waiting on us'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Approved by CAM', 'Approved by CAM')], default='New', max_length=20),
        ),
    ]
