# Generated by Django 4.2.3 on 2023-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_alter_workorder_analyst_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='analyst_approval',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reprove', 'Reprove'), ('Approved by CAM', 'Approved by CAM'), ('Approved by Analyst', 'Approved by Analyst')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cam_approval',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reprove', 'Reprove'), ('Approved by CAM', 'Approved by CAM'), ('Approved by Analyst', 'Approved by Analyst')], max_length=30, null=True),
        ),
    ]
