# Generated by Django 4.2.3 on 2023-08-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Waiting on contact', 'Waiting on contact'), ('Waiting on us', 'Waiting on us'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Approved by CAM', 'Approved by CAM'), ('Waiting Analyst', 'Waiting Analyst'), ('Approved by Analyst', 'Approved by Analyst'), ('Waiting CAM', 'Waiting CAM'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], default='New', max_length=20),
        ),
    ]
