# Generated by Django 4.2.3 on 2023-08-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_alter_workorder_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
