# Generated by Django 4.2.3 on 2023-08-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_workorder_approved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='approved_date',
            new_name='approve_date',
        ),
        migrations.AddField(
            model_name='workorder',
            name='billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
