# Generated by Django 4.2.3 on 2023-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_rename_approved_date_workorder_approve_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
