# Generated by Django 4.2.3 on 2023-09-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='recipient_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
