# Generated by Django 4.2.3 on 2023-09-11 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_customuser_is_driver_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
