# Generated by Django 4.2.3 on 2023-09-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0054_customuser_account_digit_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCpf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_cpf', models.CharField(max_length=14)),
                ('driver_cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
