# Generated by Django 4.2.3 on 2023-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_customuser_account_digit_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
