# Generated by Django 4.2.3 on 2023-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0059_alter_customuser_branch_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Checking', 'Checking'), ('Savings', 'Savings')], max_length=10, null=True),
        ),
    ]
