# Generated by Django 4.2.3 on 2023-09-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0061_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
