# Generated by Django 4.2.3 on 2023-09-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0062_alter_customuser_cnpj_alter_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
