# Generated by Django 4.2.3 on 2023-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_alter_customuser_cnpj_alter_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Driver'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
