# Generated by Django 4.2.3 on 2023-09-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_remove_drivers_email_remove_drivers_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bank',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='drivers',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
