# Generated by Django 4.2.3 on 2023-09-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0068_rename_bank_customuser_bank_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='drivers',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
