# Generated by Django 4.2.3 on 2023-09-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0070_remove_authcpf_driver_cnpj_remove_authcpf_driver_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account_type',
        ),
    ]
