# Generated by Django 4.2.3 on 2023-09-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_invoice_approval_comments_invoice_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Finance Approval', 'Finance Approval'), ('Paid', 'Paid'), ('Driver Checker', 'Driver Checker')], default='Pending', max_length=20),
        ),
    ]
