# Generated by Django 4.2.3 on 2023-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0076_invoice_operation_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='operation_approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='operation_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
