# Generated by Django 4.2.3 on 2023-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0077_invoice_operation_approval_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesValidation',
            fields=[
                ('Payroll_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Employee_ID_Number', models.IntegerField()),
                ('Pay_Period', models.DateField()),
                ('Payroll_Pay_Element', models.CharField(max_length=50)),
                ('Transaction_Type', models.CharField(max_length=50)),
                ('Element_Type', models.CharField(max_length=50)),
                ('Effective_Date', models.DateField()),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Number', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Unit_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Payroll_Effective_Date', models.DateField()),
                ('Termination_Date', models.DateField(blank=True, null=True)),
                ('Comments', models.CharField(blank=True, max_length=255, null=True)),
                ('ICP_EEPR_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('ICP_Payroll_PayElement', models.CharField(blank=True, max_length=50, null=True)),
                ('ICP_Pay_Element_Code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
