# Generated by Django 4.2.3 on 2023-09-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0078_changesvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesvalidation',
            name='Pay_Period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changesvalidation',
            name='Payroll_Effective_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
