# Generated by Django 4.2.3 on 2023-09-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0079_alter_changesvalidation_pay_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangesValidation',
        ),
    ]
