# Generated by Django 4.2.3 on 2023-09-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0081_changesvalidation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangesValidation',
        ),
    ]
