# Generated by Django 4.2.3 on 2023-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0083_changesvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesvalidation',
            name='ICP_EEPR_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
