# Generated by Django 4.2.6 on 2023-10-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0085_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='budget_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
