# Generated by Django 4.2.6 on 2023-10-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0086_company_budget_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_name', models.CharField(max_length=255)),
                ('pay_period', models.DateField(blank=True, null=True)),
                ('payroll_pay_element', models.CharField(max_length=255)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField()),
                ('unit_code', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icp_pay_element_code', models.CharField(max_length=255)),
                ('local_id', models.IntegerField(blank=True, null=True)),
                ('icp_payroll_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.company')),
            ],
        ),
    ]
